### ISSUE TITLE
Resource leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/neper#16]
Stream is opened
https://github.com/google/neper/blob/31d023a60da320a91b5f0c6004158377d1caa78e/rusage.c#L40
Opened file never closed
https://github.com/google/neper/blob/31d023a60da320a91b5f0c6004158377d1caa78e/rusage.c#L49

**Comment by gfantom** [comment]
file is closed if the `fopen` call succeeds, false alarm.

Thanks @aritrakar for bringing this to my attention
