### ISSUE TITLE
FAQ for python segmentation faults due to users having none "en_GB", LC_ALL and LANG env vars 

### ISSUE THREAD

**Issue by nikishe** [google/neper#51]
Character encodings on certain Macs cause python segmentation faults when run on the HPC.  Some Users who have  LC_ALL and LANG env vars set to sensible things given the different countries they've come from can cause segfaults when firing up an interactive Python REPL.  When LANG/LC_ALL set to something like (IIRC) en_US.utf8.  
Advice might be to set those  en_GB.utf8 on their macs or we might need to documents a different solution (eg something like dos2unix) on the cluster to fix this issue.

**Comment by nikishe** [comment]
Look at ticket SHEF240212032
 https://shef.topdesk.net/tas/secure/incident?action=lookup&lookup=naam&lookupValue=SHEF+2402+12032

**Comment by wdebruij** [comment]
This does not appear a neper issue. That URL is not publicly accessible.
